-- نظام طلبات التقديم والسير الذاتية فقط.
-- لا يمس services ولا RLS الخاص بالخدمات. نفّذه يدويًا في Supabase SQL Editor.
begin;

create table if not exists public.job_applications (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  full_name text not null check (char_length(trim(full_name)) between 2 and 120),
  phone text not null check (char_length(trim(phone)) between 7 and 30),
  email text check (email is null or char_length(email) <= 160),
  governorate text not null check (char_length(trim(governorate)) between 1 and 80),
  area text not null check (char_length(trim(area)) between 1 and 120),
  experience text check (experience is null or char_length(experience) <= 500),
  message text check (message is null or char_length(message) <= 2000),
  cv_path text not null unique,
  cv_name text not null check (char_length(cv_name) <= 180),
  cv_mime_type text not null check (cv_mime_type in ('application/pdf','image/jpeg','image/png','image/webp')),
  created_at timestamptz not null default now()
);

create index if not exists job_applications_job_id_idx on public.job_applications(job_id);
create index if not exists job_applications_created_at_idx on public.job_applications(created_at desc);

alter table public.job_applications enable row level security;

drop policy if exists job_applications_public_submit on public.job_applications;
create policy job_applications_public_submit on public.job_applications
  for insert to anon, authenticated
  with check (
    exists (select 1 from public.jobs where jobs.id = job_id and jobs.status = 'approved')
  );

drop policy if exists job_applications_admin_read on public.job_applications;
create policy job_applications_admin_read on public.job_applications
  for select to authenticated using (public.is_admin());

drop policy if exists job_applications_admin_delete on public.job_applications;
create policy job_applications_admin_delete on public.job_applications
  for delete to authenticated using (public.is_admin());

grant insert on public.job_applications to anon, authenticated;
grant select, delete on public.job_applications to authenticated;
grant usage, select on sequence public.job_applications_id_seq to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'job-applications', 'job-applications', false, 5242880,
  array['application/pdf','image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists job_application_files_public_upload on storage.objects;
create policy job_application_files_public_upload on storage.objects
  for insert to anon, authenticated
  with check (
    bucket_id = 'job-applications'
    and (storage.foldername(name))[1] ~ '^[0-9]+$'
    and exists (
      select 1 from public.jobs
      where jobs.id = ((storage.foldername(name))[1])::bigint
        and jobs.status = 'approved'
    )
    and lower(storage.extension(name)) in ('pdf','jpg','jpeg','png','webp')
  );

drop policy if exists job_application_files_admin_read on storage.objects;
create policy job_application_files_admin_read on storage.objects
  for select to authenticated
  using (bucket_id = 'job-applications' and public.is_admin());

drop policy if exists job_application_files_admin_delete on storage.objects;
create policy job_application_files_admin_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'job-applications' and public.is_admin());

commit;
