-- مطلوب تنفيذه يدويًا في Supabase SQL Editor لتفعيل قسم الوظائف.
-- يعتمد على public.is_admin() الموجودة في نظام الإدارة الحالي.
begin;

create table if not exists public.job_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text not null default 'briefcase',
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.job_slides (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text,
  image_url text not null,
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  company text not null,
  specialty text not null,
  description text not null,
  governorate text not null,
  area text not null,
  employment_type text not null check (employment_type in ('كامل','جزئي','مؤقت','عمل حر','عن بُعد','تدريب')),
  salary text,
  experience text,
  qualification text,
  phone text not null,
  image_url text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  rejection_reason text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id)
);

alter table public.jobs add column if not exists category_id bigint references public.job_categories(id) on delete set null;

alter table public.jobs enable row level security;
alter table public.job_categories enable row level security;
alter table public.job_slides enable row level security;

drop policy if exists job_categories_public_read on public.job_categories;
create policy job_categories_public_read on public.job_categories for select to anon, authenticated using (is_visible or public.is_admin());
drop policy if exists job_categories_admin_write on public.job_categories;
create policy job_categories_admin_write on public.job_categories for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists job_slides_public_read on public.job_slides;
create policy job_slides_public_read on public.job_slides for select to anon, authenticated using (is_visible or public.is_admin());
drop policy if exists job_slides_admin_write on public.job_slides;
create policy job_slides_admin_write on public.job_slides for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists jobs_public_read_approved on public.jobs;
create policy jobs_public_read_approved on public.jobs for select to anon, authenticated
  using (status = 'approved' or public.is_admin());

drop policy if exists jobs_public_submit_pending on public.jobs;
create policy jobs_public_submit_pending on public.jobs for insert to anon, authenticated
  with check (status = 'pending');

drop policy if exists jobs_admin_update on public.jobs;
create policy jobs_admin_update on public.jobs for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

grant select, insert on public.jobs to anon, authenticated;
grant update, delete on public.jobs to authenticated;
grant select on public.job_categories, public.job_slides to anon, authenticated;
grant insert, update, delete on public.job_categories, public.job_slides to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'jobs') then alter publication supabase_realtime add table public.jobs; end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'job_categories') then alter publication supabase_realtime add table public.job_categories; end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'job_slides') then alter publication supabase_realtime add table public.job_slides; end if;
  end if;
end $$;

commit;
