-- WISAL: repair the private complaint inbox read path.
-- Safe/idempotent: creates missing objects, replaces only contact_messages
-- policies/RPCs, and never deletes or updates existing complaint rows.
-- Execute only after reviewing the live Supabase schema.

CREATE TABLE IF NOT EXISTS public.contact_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_type text NOT NULL DEFAULT 'other',
  message text NOT NULL DEFAULT '',
  image_url text,
  owner_uid uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'new',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS contact_messages_insert_policy ON public.contact_messages;
DROP POLICY IF EXISTS contact_messages_select_policy ON public.contact_messages;
DROP POLICY IF EXISTS contact_messages_update_policy ON public.contact_messages;
DROP POLICY IF EXISTS contact_messages_delete_policy ON public.contact_messages;
DROP POLICY IF EXISTS wisal_contact_messages_select_gate ON public.contact_messages;
DROP POLICY IF EXISTS wisal_contact_messages_update_gate ON public.contact_messages;
DROP POLICY IF EXISTS wisal_contact_messages_delete_gate ON public.contact_messages;

CREATE POLICY contact_messages_insert_policy
  ON public.contact_messages
  AS PERMISSIVE FOR INSERT
  TO anon, authenticated
  WITH CHECK (
    status = 'new'
    AND length(trim(message)) > 0
    AND length(message) <= 1000
  );

CREATE POLICY contact_messages_select_policy
  ON public.contact_messages
  AS PERMISSIVE FOR SELECT
  TO authenticated
  USING (public.is_admin());

CREATE POLICY contact_messages_update_policy
  ON public.contact_messages
  AS PERMISSIVE FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

CREATE POLICY contact_messages_delete_policy
  ON public.contact_messages
  AS PERMISSIVE FOR DELETE
  TO authenticated
  USING (public.is_admin());

-- Restrictive gates make older permissive policies unable to expose complaints
-- to ordinary users if a historical migration left one behind.
CREATE POLICY wisal_contact_messages_select_gate
  ON public.contact_messages
  AS RESTRICTIVE FOR SELECT
  TO anon, authenticated
  USING (public.is_admin());

CREATE POLICY wisal_contact_messages_update_gate
  ON public.contact_messages
  AS RESTRICTIVE FOR UPDATE
  TO anon, authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

CREATE POLICY wisal_contact_messages_delete_gate
  ON public.contact_messages
  AS RESTRICTIVE FOR DELETE
  TO anon, authenticated
  USING (public.is_admin());

REVOKE ALL ON TABLE public.contact_messages FROM anon, authenticated;
GRANT INSERT ON TABLE public.contact_messages TO anon, authenticated;
GRANT SELECT, UPDATE, DELETE ON TABLE public.contact_messages TO authenticated;

DO $grant_sequence$
DECLARE
  sequence_name text;
BEGIN
  sequence_name := pg_get_serial_sequence('public.contact_messages', 'id');
  IF sequence_name IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO anon, authenticated', sequence_name);
  END IF;
END
$grant_sequence$;

CREATE OR REPLACE FUNCTION public.admin_list_contact_messages()
RETURNS SETOF public.contact_messages
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'admin authorization required' USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
    SELECT messages.*
    FROM public.contact_messages AS messages
    ORDER BY messages.created_at DESC;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_set_contact_message_status(
  p_id bigint,
  p_status text
)
RETURNS public.contact_messages
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  updated public.contact_messages%ROWTYPE;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'admin authorization required' USING ERRCODE = '42501';
  END IF;
  IF p_status NOT IN ('new', 'review', 'resolved') THEN
    RAISE EXCEPTION 'invalid contact message status' USING ERRCODE = '22023';
  END IF;

  UPDATE public.contact_messages
     SET status = p_status,
         updated_at = now()
   WHERE id = p_id
   RETURNING * INTO updated;
  RETURN updated;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_delete_contact_message(p_id bigint)
RETURNS public.contact_messages
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  deleted public.contact_messages%ROWTYPE;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'admin authorization required' USING ERRCODE = '42501';
  END IF;

  DELETE FROM public.contact_messages
  WHERE id = p_id
  RETURNING * INTO deleted;
  RETURN deleted;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_list_contact_messages() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_contact_messages() TO authenticated;
REVOKE ALL ON FUNCTION public.admin_set_contact_message_status(bigint, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_contact_message_status(bigint, text) TO authenticated;
REVOKE ALL ON FUNCTION public.admin_delete_contact_message(bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_contact_message(bigint) TO authenticated;
