-- ============================================================
-- Saleen Service: secure contact messages / suggestions
-- This migration is intentionally isolated to public.contact_messages.
-- It assumes the existing public.is_admin() helper from the current
-- authenticated administration system is already installed.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.contact_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_type text NOT NULL DEFAULT 'other'
    CHECK (message_type IN ('bug', 'suggestion', 'advice', 'complaint', 'other')),
  message text NOT NULL DEFAULT ''
    CHECK (length(trim(message)) > 0 AND length(message) <= 1000),
  image_url text,
  owner_id text,
  status text NOT NULL DEFAULT 'new'
    CHECK (status IN ('new', 'review', 'resolved')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS contact_messages_created_at_idx
  ON public.contact_messages (created_at DESC);

-- Keep the required default even when the table already existed.
ALTER TABLE public.contact_messages
  ALTER COLUMN status SET DEFAULT 'new';

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

-- Recreate only policies belonging to public.contact_messages.
DROP POLICY IF EXISTS "contact_messages_insert_policy" ON public.contact_messages;
DROP POLICY IF EXISTS "contact_messages_select_policy" ON public.contact_messages;
DROP POLICY IF EXISTS "contact_messages_update_policy" ON public.contact_messages;
DROP POLICY IF EXISTS "contact_messages_delete_policy" ON public.contact_messages;

-- Visitors and authenticated users may submit messages, but cannot choose an
-- administrative state: every accepted INSERT must have status = 'new'.
CREATE POLICY "contact_messages_insert_policy"
  ON public.contact_messages
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (
    status = 'new'
    AND length(trim(message)) > 0
    AND length(message) <= 1000
  );

-- Reading the inbox is restricted to authenticated administrators.
CREATE POLICY "contact_messages_select_policy"
  ON public.contact_messages
  FOR SELECT
  TO authenticated
  USING (public.is_admin());

-- Only authenticated administrators may update messages or their status.
CREATE POLICY "contact_messages_update_policy"
  ON public.contact_messages
  FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- Only authenticated administrators may delete messages.
CREATE POLICY "contact_messages_delete_policy"
  ON public.contact_messages
  FOR DELETE
  TO authenticated
  USING (public.is_admin());
