-- ============================================================
-- Migration: تفاعلات الاقتراحات (Reactions + Comments)
-- منفصل تمامًا عن service_comments / service_reactions
-- يُنفذ في: Supabase Dashboard → SQL Editor
-- ============================================================

-- ============================================================
-- 1) جدول التفاعلات: public.suggestion_reactions
-- ============================================================
CREATE TABLE IF NOT EXISTS public.suggestion_reactions (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  suggestion_id bigint NOT NULL
                  REFERENCES public.comments(id) ON DELETE CASCADE,
  owner_id      text   NOT NULL,
  reaction_type text   NOT NULL DEFAULT 'like',
  created_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT suggestion_reactions_unique_per_owner
    UNIQUE (suggestion_id, owner_id, reaction_type)
);

CREATE INDEX IF NOT EXISTS suggestion_reactions_suggestion_id_idx
  ON public.suggestion_reactions (suggestion_id);

ALTER TABLE public.suggestion_reactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "sr_select_policy"   ON public.suggestion_reactions;
DROP POLICY IF EXISTS "sr_insert_policy"   ON public.suggestion_reactions;
DROP POLICY IF EXISTS "sr_delete_policy"   ON public.suggestion_reactions;

-- SELECT: عام (عدّادات مرئية للجميع)
CREATE POLICY "sr_select_policy" ON public.suggestion_reactions
  FOR SELECT USING (true);

-- INSERT: معرّف جهاز صالح مطلوب
CREATE POLICY "sr_insert_policy" ON public.suggestion_reactions
  FOR INSERT WITH CHECK (
    owner_id IS NOT NULL AND length(trim(owner_id)) > 0
  );

-- DELETE: معرّف جهاز صالح مطلوب (التطبيق يفرض أن المالك فقط يحذف عبر .eq owner_id)
CREATE POLICY "sr_delete_policy" ON public.suggestion_reactions
  FOR DELETE USING (
    owner_id IS NOT NULL AND length(trim(owner_id)) > 0
  );

GRANT SELECT, INSERT, DELETE ON public.suggestion_reactions
  TO anon, authenticated;


-- ============================================================
-- 2) جدول التعليقات: public.suggestion_comments
-- ============================================================
CREATE TABLE IF NOT EXISTS public.suggestion_comments (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  suggestion_id bigint NOT NULL
                  REFERENCES public.comments(id) ON DELETE CASCADE,
  content       text   NOT NULL,
  owner_id      text   NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT suggestion_comments_not_empty
    CHECK (length(trim(content)) > 0 AND length(content) <= 300)
);

CREATE INDEX IF NOT EXISTS suggestion_comments_suggestion_id_idx
  ON public.suggestion_comments (suggestion_id, created_at);

ALTER TABLE public.suggestion_comments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "sc_select_policy" ON public.suggestion_comments;
DROP POLICY IF EXISTS "sc_insert_policy" ON public.suggestion_comments;
DROP POLICY IF EXISTS "sc_delete_policy" ON public.suggestion_comments;

-- SELECT: عام
CREATE POLICY "sc_select_policy" ON public.suggestion_comments
  FOR SELECT USING (true);

-- INSERT: معرّف جهاز صالح + محتوى غير فارغ
CREATE POLICY "sc_insert_policy" ON public.suggestion_comments
  FOR INSERT WITH CHECK (
    owner_id IS NOT NULL AND length(trim(owner_id)) > 0
    AND length(trim(content)) > 0
  );

-- DELETE: معرّف جهاز صالح مطلوب (التطبيق يفرض أن المالك فقط يحذف عبر .eq owner_id)
CREATE POLICY "sc_delete_policy" ON public.suggestion_comments
  FOR DELETE USING (
    owner_id IS NOT NULL AND length(trim(owner_id)) > 0
  );

GRANT SELECT, INSERT, DELETE ON public.suggestion_comments
  TO anon, authenticated;
